// GENERATED CODE - DO NOT MODIFY BY HAND
// ignore_for_file: type=lint

// ============================================================
//  This file imports all Hive type adapters and registers them.
//  Generated by build_runner — re-run after model changes.
// ============================================================

import 'package:hive_flutter/hive_flutter.dart';

import '../sync/write_queue_entry.dart';

/// Open all Hive boxes used by the app.
/// Call this from [main] before [runApp].
Future<void> initHive() async {
  await Hive.initFlutter();

  // Register adapters
  if (!Hive.isAdapterRegistered(10)) {
    Hive.registerAdapter(WriteQueueEntryAdapter());
  }

  // Open boxes
  await Hive.openBox<WriteQueueEntry>('write_queue');
  await Hive.openBox<dynamic>('settings');
  await Hive.openBox<dynamic>('session');
  await Hive.openBox<dynamic>('menus');
}
